### ISSUE TITLE
unable to reconnect to MQTT if disconnected

### ISSUE THREAD

**Issue by devasheeshG** [Jarvis-AI-project/JARVARIAN-FIRMWARE-HOME-AUTOMATION#8]

**Comment by devasheeshG** [comment]
completed

**Comment by SWARNIM-BURNWAL** [comment]
Serial initialized
-----------------------
Mounted LittleFS
-----------------------
Opened config file
Closed config file
-----------------------
Config file loaded successfully:
-----------------------
Parsed JSON successfully
-----------------------
WIFI_SSID:      SWARNIM-4G
WIFI_PASS:      SWARNIM14032004
WIFI_HOSTNAME:  IOT-ESP8266
WIFI_IP:        192.168.29.240
WIFI_GATEWAY:   192.168.29.1
WIFI_SUBNET:    255.255.255.0
WIFI_DNS:       192.168.29.1
MQTT_CLIENT_ID:         Bedroom
MQTT_SERVER:    192.168.29.245
MQTT_PORT:      1883
MQTT_USERNAME:  mosquitto
MQTT_PASSWORD:  mosquitto
MQTT_TOPIC:     home/gamingroom
-----------------------
Initialized BLUE_LED on pin 2 as OUTPUT

assert failed: tcpip_send_msg_wait_sem IDF/components/lwip/lwip/src/api/tcpip.c:455 (Invalid mbox)


Backtrace: 0x400835a1:0x3ffca320 0x4008b7ad:0x3ffca340 0x40090c2d:0x3ffca360 0x400f48e5:0x3ffca490 0x40104dcd:0x3ffca4c0 0x40104e2d:0x3ffca4e0 0x400f40bd:0x3ffca530 0x4014c3fe:0x3ffca550 0x4014c478:0x3ffca5a0 0x400d9e2d:0x3ffca5c0 0x400d6b73:0x3ffca5e0 0x400dfd66:0x3ffcae80




ELF file SHA256: 7d35286e7743d4a4

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
-----------------------
Serial initialized




not working for esp32 Have a Look To it

**Comment by devasheeshG** [comment]
it is fixed in `eeprom-support` branch. will be merged in the next release.
